worker: don't use CUDA as base image
SubstraFoundation/substra-backend pull request #320
Opened 2020-09-14 22:13 UTC by AurelienGasser

The CUDA image isn't necessary in the worker anymore.

Use the python image to improve cache reuse across generated docker images (substra-backend / celeryworker / celerybeat)

2020-09-14 22:14 UTC, AurelienGasser commented
e2e :heavy_check_mark:

2020-09-15 07:42 UTC, inalgnu approved these changes

2020-09-15 08:33 UTC, Kelvin-M commented
Looks like celeryworker and celerybeat have the same dockerfile. It may be better to merge them and use the same image for both services :)

2020-09-15 13:22 UTC, Kelvin-M requested changes
Make celery image unique for celery worker and celery beat :D

2020-09-15 13:31 UTC, inalgnu commented
@Kelvin-M Good idea, but looks like not the purpose of this pull request

2020-09-15 13:33 UTC, Kelvin-M approved these changes
I will do the rest of the work suggested in another PR

2020-09-15 13:35 UTC, AurelienGasser commented
@Kelvin-M Awesome! Merging this for now.

2020-09-15 13:35 UTC, merged