Simplify celery images
SubstraFoundation/substra-backend pull request #323
Opened 2020-09-15 14:05 UTC by Kelvin-M

As https://github.com/SubstraFoundation/substra-backend/pull/320 has been merged, we can simplify celery services images to only one.

@AlexandrePicosson  we may need to update docker-hub to take this into account

Companion PR
https://github.com/SubstraFoundation/substra-tests/pull/146

2020-09-15 14:28 UTC, AurelienGasser requested changes
Just a minor oversight in the README

2020-09-15 14:28 UTC, AurelienGasser commented on README.md
>  |  substra-backend | celeryworker | celerybeat | flower |
you fogot this line

2020-09-15 14:31 UTC, Kelvin-M commented on README.md
>  |  substra-backend | celeryworker | celerybeat | flower |
Fixed, thank you !

2020-09-15 14:44 UTC, AurelienGasser approved these changes

2020-09-15 14:55 UTC, AurelienGasser commented
@Kelvin-M Have you considered bumping the chart?

2020-09-16 07:59 UTC, AlexandrePicosson approved these changes
Sure I will create the repository on DockerHub, just let me know when this gets merged.

Maybe we should also define a time for when we will retire the old images, is there a way to manage EOL for versions somewhere for example ?
Or do we keep the old images/repository for an infinite amount of time ?

2020-09-16 08:56 UTC, Kelvin-M commented
@AlexandrePicosson we may need to create it before this branch is merged no ?

For old images, I don't know. We may keep it like this and when we won't support them anymore remove them (maybe in 2021) ?

2020-09-16 09:08 UTC, AlexandrePicosson commented
It does not matter, when creating the repo we can trigger a manual build so it should be okay, I'll look into this now.

I have no strong opinion on the subject, I just wanted to know if there is already a policy for this kind of situations. Just deleting it when we drop the support of the last version is fine for me.

2020-09-16 09:15 UTC, AlexandrePicosson commented
I created the DockerHub repository here : https://hub.docker.com/repository/docker/substrafoundation/celery

2020-09-17 15:21 UTC, AurelienGasser commented
@Kelvin-M I think you forgot to update the `chart/CHANGELOG.md`

2020-09-18 07:41 UTC, AlexandrePicosson approved these changes

2020-09-18 07:42 UTC, inalgnu approved these changes

2020-09-21 15:10 UTC, merged